import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DashboardHeader from "@/components/navbar";
import Sidebar from "@/components/sidebar";
import DateRangeSelector from "@/components/daterange";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col h-[100vh]"> 
          <DashboardHeader />
          <div className="flex">
            <Sidebar/>
            <div className="p-[20px] w-screen"> {children} </div>
            
          </div>
        </div>
      </body>
    </html>
  );
}
